-- 
-- generated by pimp v1.2
-- 
-- (c) 2018-19, IT-Gears.hu
-- 
-- Author: Janos Bali
--
--
local pfont= require "pimp.pfont"
local pimpCore = require "pimp.core"
local dict = require "pimp.dictionary"

local m={}
local objectOptions = {}
function m.getObjectOptions()
  return objectOptions
end
function m.getSceneObjects(event,sceneGroup)
  local opt, obj
  local sceneObjects = {}
  
	objectOptions["designRect"] = {
	id = "designRect",
	type = "Rect",
	isVisible = true,
	x = 0,
	y = 48,
	width = 720,
	height = 80,
	cornerRadius = 0,
	strokeWidth = 0,
	fillColor = {1,1,0.8,0.47843137254902},
	strokeColor = {0,0,0,0},
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newRect (objectOptions["designRect"])
	obj.id = "designRect"
	obj.isVisible = true
	sceneObjects["designRect"] = obj

	objectOptions["My_MaterialIcon"] = {
	id = "My_MaterialIcon",
	type = "MaterialIcon",
	isVisible = true,
	text = mIcon.get("info_outline"),
	x = 23 - 48/4,
	y = 64 - 48/8,
	width = 48,
	height = 48,
	font = pfont.get('MaterialIcons'),
	fontSize = 48,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newMaterialIcon (objectOptions["My_MaterialIcon"])
	obj.id = "My_MaterialIcon"
	obj.isVisible = true
	sceneObjects["My_MaterialIcon"] = obj

	objectOptions["My_MaterialIcon2"] = {
	id = "My_MaterialIcon2",
	type = "MaterialIcon",
	isVisible = true,
	text = mIcon.get("arrow_back"),
	x = 650 - 48/4,
	y = 64 - 48/8,
	width = 48,
	height = 48,
	font = pfont.get('MaterialIcons'),
	fontSize = 48,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	sceneGroup = sceneGroup,
	reference = "testapp.Page01",
	}
	obj = pimpCore.newMaterialIcon (objectOptions["My_MaterialIcon2"])
	obj.id = "My_MaterialIcon2"
	obj.isVisible = true
	sceneObjects["My_MaterialIcon2"] = obj

	objectOptions["My_Text"] = {
	id = "My_Text",
	type = "Text",
	isVisible = true,
	text = [[Application Title]],
	x = 251,
	y = 70,
	font = native.systemFont,
	fontSize = 12,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	width = 262,
	height = 0,
	align= "center",
	valign= "top",
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newText (objectOptions["My_Text"])
	obj.id = "My_Text"
	obj.isVisible = true
	sceneObjects["My_Text"] = obj

	objectOptions["My_Text2"] = {
	id = "My_Text2",
	type = "Text",
	isVisible = true,
	text = [[Back]],
	x = 0,
	y = 107,
	font = native.systemFont,
	fontSize = 12,
	fillColor = {1,0.54901960784314,0.23137254901961,0.92941176470588},
	width = 702,
	height = 0,
	align= "right",
	valign= "middle",
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newText (objectOptions["My_Text2"])
	obj.id = "My_Text2"
	obj.isVisible = true
	sceneObjects["My_Text2"] = obj

	objectOptions["email_Page02"] = {
	id = "email_Page02",
	type = "Text",
	isVisible = true,
	text = [[Thank you!]],
	x = 0,
	y = 180,
	font = native.systemFont,
	fontSize = 12,
	fillColor = {0.8,0.2,0.8,0.92941176470588},
	width = 720,
	height = 0,
	align= "center",
	valign= "top",
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newText (objectOptions["email_Page02"])
	obj.id = "email_Page02"
	obj.isVisible = true
	sceneObjects["email_Page02"] = obj

	objectOptions["My_Image"] = {
	id = "My_Image",
	type = "Image",
	isVisible = true,
	image = "e8512e764a0e489b95cad554d58fb4ee.jpg",
	width = 468,
	height = 336,
	x = 134,
	y = 215,
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newImageRect (objectOptions["My_Image"])
	obj.id = "My_Image"
	obj.isVisible = true
	sceneObjects["My_Image"] = obj

	objectOptions["My_WebView"] = {
	id = "My_WebView",
	type = "newWebView",
	isVisible = true,
	genericType = "newWebView",
	hasText = false,
	hasRect = false,
	hasOverColors = false,
	x = 0,
	y = 585,
	width = 720,
	height = 695.7031250000001,
	urlRequest="https://coronalabs.com/blog",
canGoForward = true,
canGoBack = true,
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newGenericObject (objectOptions["My_WebView"])
	obj.id = "My_WebView"
	obj.isVisible = true
	sceneObjects["My_WebView"] = obj

  return sceneObjects
end
return m
