-- 
-- generated by pimp v1.2
-- 
-- (c) 2018-19, IT-Gears.hu
-- 
-- Author: Janos Bali
--
--
local pfont= require "pimp.pfont"
local pimpCore = require "pimp.core"
local dict = require "pimp.dictionary"

local m={}
local objectOptions = {}
function m.getObjectOptions()
  return objectOptions
end
function m.getSceneObjects(event,sceneGroup)
  local opt, obj
  local sceneObjects = {}
  
	objectOptions["My_Button"] = {
	id = "My_Button",
	type = "Button",
	isVisible = true,
	label = [[Submit]],
	shape = "roundedRect",
	cornerRadius = 16,
	strokeWidth = 5,
	x = 281,
	y = 600,
	width = 200,
	height = 40,
	font = native.systemFont,
	fontSize = 20,
	labelColor  = { default={0,0,0.4,0.47843137254902}, over={0,0,0,0.058823529411765} },
	fillColor = { default={0.34509803921569,0.50196078431373,0.8,0}, over={0,0,0,0.12156862745098} },
	strokeColor  = { default={0.34509803921569,0.50196078431373,0.8,0.47843137254902}, over={0,0,0,0.058823529411765} },
	sceneGroup = sceneGroup,
	reference = "testapp.Page02",
	}
	obj = pimpCore.newButton (objectOptions["My_Button"])
	obj.id = "My_Button"
	obj.isVisible = true
	sceneObjects["My_Button"] = obj

	objectOptions["emailInput"] = {
	id = "emailInput",
	type = "newTextField",
	isVisible = true,
	genericType = "newTextField",
	hasText = true,
	hasRect = true,
	hasOverColors = false,
	x = 232,
	y = 495,
	width = 300,
	height = 40,
	strokeWidth = 4,
	text = [[your email address...]],
	font = native.systemFont,
	fontSize = 20,
	align= "center",
	fillColor = { 1,1,0.8,0.50980392156863},
	strokeColor = { 1,0.54901960784314,0.23137254901961,0.12156862745098},
	textColor = { 0.6,0.6,0.6,1},
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newGenericObject (objectOptions["emailInput"])
	obj.id = "emailInput"
	obj.isVisible = true
	sceneObjects["emailInput"] = obj

	objectOptions["infoTextBox"] = {
	id = "infoTextBox",
	type = "newTextBox",
	isVisible = true,
	genericType = "newTextBox",
	hasText = true,
	hasRect = false,
	hasOverColors = false,
	x = 0,
	y = 180,
	width = 720,
	height = 220,
	text = [[Shapes in a collection tend to have the same style such as same font, color, stroke style... To be convenient to stencil authors in this situation, Pencil supports grouping all shapes common style to collection style. These collection properties can be used as the default value for stencil properties. Then if collection style is changed, default property values for shapes will be changed accordingly. Have a look at this example. Collection properties are defined and then used in shape properties.]],
	font = pfont.get('Arial'),
	fontSize = 20,
	align= "center",
	textColor = { 0.12941176470588,0.12941176470588,0.12941176470588,1},
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newGenericObject (objectOptions["infoTextBox"])
	obj.id = "infoTextBox"
	obj.isVisible = true
	sceneObjects["infoTextBox"] = obj

	objectOptions["My_Text"] = {
	id = "My_Text",
	type = "Text",
	isVisible = true,
	text = [[Enter your e-mail address:]],
	x = 0,
	y = 450,
	font = native.systemFont,
	fontSize = 12,
	fillColor = {1,0.54901960784314,0.23137254901961,0.92941176470588},
	width = 720,
	height = 0,
	align= "center",
	valign= "middle",
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newText (objectOptions["My_Text"])
	obj.id = "My_Text"
	obj.isVisible = true
	sceneObjects["My_Text"] = obj

	objectOptions["designRect"] = {
	id = "designRect",
	type = "Rect",
	isVisible = true,
	x = 0,
	y = 1200,
	width = 720,
	height = 80,
	cornerRadius = 0,
	strokeWidth = 0,
	fillColor = {1,1,0.8,0.47843137254902},
	strokeColor = {0,0,0,0},
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newRect (objectOptions["designRect"])
	obj.id = "designRect"
	obj.isVisible = true
	sceneObjects["designRect"] = obj

	objectOptions["My_MapView"] = {
	id = "My_MapView",
	type = "newMapView",
	isVisible = true,
	genericType = "newMapView",
	hasText = false,
	hasRect = false,
	hasOverColors = false,
	x = 0,
	y = 670,
	width = 720,
	height = 500,
	isLocationVisible = true,
isScrollEnabled = true,
isZoomEnabled = true,

	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newGenericObject (objectOptions["My_MapView"])
	obj.id = "My_MapView"
	obj.isVisible = true
	sceneObjects["My_MapView"] = obj

	objectOptions["designRect2"] = {
	id = "designRect2",
	type = "Rect",
	isVisible = true,
	x = 0,
	y = 48,
	width = 720,
	height = 80,
	cornerRadius = 0,
	strokeWidth = 0,
	fillColor = {1,1,0.8,0.47843137254902},
	strokeColor = {0,0,0,0},
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newRect (objectOptions["designRect2"])
	obj.id = "designRect2"
	obj.isVisible = true
	sceneObjects["designRect2"] = obj

	objectOptions["My_MaterialIcon"] = {
	id = "My_MaterialIcon",
	type = "MaterialIcon",
	isVisible = true,
	text = mIcon.get("info_outline"),
	x = 23 - 48/4,
	y = 64 - 48/8,
	width = 48,
	height = 48,
	font = pfont.get('MaterialIcons'),
	fontSize = 48,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newMaterialIcon (objectOptions["My_MaterialIcon"])
	obj.id = "My_MaterialIcon"
	obj.isVisible = true
	sceneObjects["My_MaterialIcon"] = obj

	objectOptions["My_MaterialIcon2"] = {
	id = "My_MaterialIcon2",
	type = "MaterialIcon",
	isVisible = true,
	text = mIcon.get("arrow_forward"),
	x = 650 - 48/4,
	y = 64 - 48/8,
	width = 48,
	height = 48,
	font = pfont.get('MaterialIcons'),
	fontSize = 48,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	sceneGroup = sceneGroup,
	reference = "testapp.Page02",
	}
	obj = pimpCore.newMaterialIcon (objectOptions["My_MaterialIcon2"])
	obj.id = "My_MaterialIcon2"
	obj.isVisible = true
	sceneObjects["My_MaterialIcon2"] = obj

	objectOptions["My_Text2"] = {
	id = "My_Text2",
	type = "Text",
	isVisible = true,
	text = [[Application Title]],
	x = 251,
	y = 70,
	font = native.systemFont,
	fontSize = 12,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	width = 262,
	height = 0,
	align= "center",
	valign= "top",
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newText (objectOptions["My_Text2"])
	obj.id = "My_Text2"
	obj.isVisible = true
	sceneObjects["My_Text2"] = obj

	objectOptions["My_Text3"] = {
	id = "My_Text3",
	type = "Text",
	isVisible = true,
	text = [[Forward]],
	x = 0,
	y = 107,
	font = native.systemFont,
	fontSize = 12,
	fillColor = {1,0.54901960784314,0.23137254901961,0.92941176470588},
	width = 715,
	height = 0,
	align= "right",
	valign= "middle",
	sceneGroup = sceneGroup,
	}
	obj = pimpCore.newText (objectOptions["My_Text3"])
	obj.id = "My_Text3"
	obj.isVisible = true
	sceneObjects["My_Text3"] = obj

  return sceneObjects
end
return m
