-- 
-- generated by pimp v1.1
-- 
-- (c) 2018, IT-Gears.hu
-- 
-- Author: Janos Bali
--
local pimp = require "export.pimp_Page01"
local composer = require "composer"
local scene = composer.newScene()

function scene:create(event)
  local sceneGroup = self.view
  local objects = pimp.getSceneObjects(event,sceneGroup)
end

scene:addEventListener( "create", scene )

return scene
