-- 
-- generated by pimp v1.1
-- 
-- (c) 2018, IT-Gears.hu
-- 
-- Author: Janos Bali
--
--
local pimp = require "export.pimp_Page02"
local pimpCore = require "pimp.pimpCore"
local composer = require "composer"
local scene = composer.newScene()

local sceneObjects
local objectOptions

function scene:create(event)
  local sceneGroup = self.view
  sceneObjects = pimp.getSceneObjects(event,sceneGroup)
  objectOptions = pimp.getObjectOptions()
end

function scene:show(event)
  local sceneGroup = self.view
  if event.phase=="did" then
    pimpCore.showNativeObjects(sceneObjects,objectOptions)
  end
end

function scene:hide(event)
  local sceneGroup = self.view
  if event.phase=="did" then
    pimpCore.hideNativeObjects(sceneObjects,objectOptions)
  end
end

function scene:destroy( event )
  local sceneGroup = self.view
end

scene:addEventListener( "create", scene )
scene:addEventListener( "show", scene )
scene:addEventListener( "hide", scene )
scene:addEventListener( "destroy", scene )

return scene
