-- 
-- generated by pimp v1.0
-- 
-- (c) 2018, IT-Gears.hu
-- 
-- Author: Janos Bali
--
local pimpCore = require "pimp.pimpCore"
local m={}
function m.getSceneObjects(event,sceneGroup)
  local obj
  local sceneObjects = {}
  
	obj = pimpCore.newRect {
	id = "designRect",
	x = 0,
	y = 48,
	width = 720,
	height = 80,
	cornerRadius = 0,
	strokeWidth = 0,
	fillColor = {1,1,0.8,0.47843137254902},
	strokeColor = {0,0,0,0},
	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["designRect"] = obj
	obj.isVisible = true

	obj = pimpCore.newMaterialIcon {
	id = "My_MaterialIcon",
	text = mIcon.get("info_outline"),
	x = 23,
	y = 64,
	width = 48,
	height = 48,
	font = mFont,
	fontSize = 48,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["My_MaterialIcon"] = obj
	obj.isVisible = true

	obj = pimpCore.newMaterialIcon {
	id = "My_MaterialIcon2",
	text = mIcon.get("menu"),
	x = 650,
	y = 64,
	width = 48,
	height = 48,
	font = mFont,
	fontSize = 48,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["My_MaterialIcon2"] = obj
	obj.isVisible = true

	obj = pimpCore.newButton {
	id = "My_Button",
	label = "Submit",
	shape = "roundedRect",
	cornerRadius = 16,
	strokeWidth = 5,
	x = 281,
	y = 600,
	width = 200,
	height = 40,
	font = native.systemFont,
	fontSize = 20,
	labelColor  = { default={0,0,0.4,0.47843137254902}, over={0,0,0,0.058823529411765} },
	fillColor = { default={0.34509803921569,0.50196078431373,0.8,0}, over={0,0,0,0.12156862745098} },
	strokeColor  = { default={0.34509803921569,0.50196078431373,0.8,0.47843137254902}, over={0,0,0,0.058823529411765} },
	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["My_Button"] = obj
	obj.isVisible = true

	obj = pimpCore.newGenericObject {
	id = "My_Widget",
	genericType = "newTextField",
	hasText = true,
	hasRect = true,
	hasOverColors = false,
	x = 232,
	y = 495,
	width = 300,
	height = 40,
	strokeWidth = 4,
	text = [[your email address...]],
	font = native.systemFont,
	fontSize = 20,
	align= "center",
	fillColor = { 1,1,0.8,0.50980392156863},
	strokeColor = { 1,0.54901960784314,0.23137254901961,0.12156862745098},
	textColor = { 0.6,0.6,0.6,1},
	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["My_Widget"] = obj
	obj.isVisible = true

	obj = pimpCore.newGenericObject {
	id = "My_Widget2",
	genericType = "newTextBox",
	hasText = true,
	hasRect = true,
	hasOverColors = false,
	x = 0,
	y = 180,
	width = 720,
	height = 220,
	strokeWidth = 0,
	text = [[Shapes in a collection tend to have the same style such as same font, color, stroke style... To be convenient to stencil authors in this situation, Pencil supports grouping all shapes common style to collection style. These collection properties can be used as the default value for stencil properties. Then if collection style is changed, default property values for shapes will be changed accordingly. Have a look at this example. Collection properties are defined and then used in shape properties.]],
	font = native.systemFont,
	fontSize = 20,
	align= "left",
	fillColor = { 1,1,0.8,0},
	strokeColor = { 0,0,0,0},
	textColor = { 0.12941176470588,0.12941176470588,0.12941176470588,1},
	isEditable = false,

	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["My_Widget2"] = obj
	obj.isVisible = true

	obj = pimpCore.newText {
	id = "My_Text",
	text = "E-mail address",
	x = 298,
	y = 455,
	font = native.systemFont,
	fontSize = 24,
	fillColor = {1,0.54901960784314,0.23137254901961,0.92941176470588},
	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["My_Text"] = obj
	obj.isVisible = true

	obj = pimpCore.newText {
	id = "My_Text2",
	text = "Application Title",
	x = 251,
	y = 70,
	font = native.systemFont,
	fontSize = 36,
	fillColor = {0.34509803921569,0.50196078431373,0.8,0.47843137254902},
	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["My_Text2"] = obj
	obj.isVisible = true

	obj = pimpCore.newRect {
	id = "designRect2",
	x = 0,
	y = 1200,
	width = 720,
	height = 80,
	cornerRadius = 0,
	strokeWidth = 0,
	fillColor = {1,1,0.8,0.47843137254902},
	strokeColor = {0,0,0,0},
	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["designRect2"] = obj
	obj.isVisible = true

	obj = pimpCore.newGenericObject {
	id = "My_MapView",
	genericType = "newMapView",
	hasText = false,
	hasRect = false,
	hasOverColors = false,
	x = 0,
	y = 670,
	width = 720,
	height = 500,
	isLocationVisible = true,
isScrollEnabled = true,
isZoomEnabled = true,

	sceneGroup = sceneGroup,
	reference = nil,
	}
	sceneObjects["My_MapView"] = obj
	obj.isVisible = true

  return sceneObjects
end
return m
