-- 
-- generated by pimp v1.2
-- 
-- (c) 2018-19, IT-Gears.hu
-- 
-- Author: Janos Bali
--
--
local composer = require "composer"
local pimpCore = require "pimp.core"
local dict = require "pimp.dictionary"
local pimp = require "testapp.pimp.Page01"

local scene = composer.newScene()

local sceneObjects
local objectOptions

function scene:create(event)
  local sceneGroup = self.view
  sceneObjects = pimp.getSceneObjects(event,sceneGroup)
  objectOptions = pimp.getObjectOptions()
end

function scene:show(event)
  if event.phase=="will" then
    for o,t in pairs(sceneObjects) do
      if objectOptions[o].translate then 
        sceneObjects[o].text = dict.get(objectOptions[o].text)
      end
    end
    pimpCore.showNativeObjects(sceneObjects,objectOptions)
  end
end

function scene:hide(event)
  if event.phase=="did" then
    pimpCore.hideNativeObjects(sceneObjects,objectOptions)
  end
end

function scene:destroy( event)
  pimpCore.destroyNativeObjects(sceneObjects,objectOptions)
end

scene:addEventListener( "create", scene )
scene:addEventListener( "show", scene )
scene:addEventListener( "hide", scene )
scene:addEventListener( "destroy", scene )

return scene
